### ISSUE TITLE
Databinding methods such as Eval(), XPath(), and Bind() can only be used in the context of a databound control

### ISSUE THREAD

**Issue by yurigo** [DevExpress-Examples/how-to-use-two-way-data-bound-aspxgridlookup-in-edit-form-of-aspxgridview-to-edit-data-e2979#1]
I've found this error message over and over when i tried to bind a aspxgridlookup in side the EditItemTemplate in my project.

I tried to test this example and it worked fine...

But trying to reproduce the error i found that if set the property of the ASPxGridview SettingsEditing-Mode to "PopupEditForm" shows the error and stops working.

```
<dx:ASPxGridView ID="grid" runat="server" AutoGenerateColumns="False" DataSourceID="dsProducts" KeyFieldName="ProductID" OnRowInserting="grid_RowInserting" OnRowUpdating="grid_RowUpdating">
            
   <SettingsEditing Mode="PopupEditForm">
   </SettingsEditing>
            
   <Columns>
      ...
   </Columns>

</dx:ASPxGridView>
```

**Comment by Artem-Babich** [comment]
Hello @yurigo , 
I tried to reproduce the problem, but without success:
![YgAv0bWMfr](https://user-images.githubusercontent.com/51639399/61540726-da651100-aa46-11e9-9609-bfca9185f8e2.gif)
I am using the latest version (19.1.4) of the DX controls.
Try this version on your side and let us know your results.
If the problem persists, create a ticket in our [Support Center](https://www.devexpress.com/Support/Center/)
